import { Inter } from "next/font/google";
import "./globals.css"; // Global Tailwind CSS or any global styles
import Header from "./_components/Header";
import AuthModal from "./_components/AuthModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Common layout elements go here */}
        <Header />
        <AuthModal />
        
        {/* Render the active page */}
        {children}
      </body>
    </html>
  );
}
